name: Tagged Build

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      # Lets us use one-liner JSON manipulations on package.jsons
      - run: "npm install -g json"

      # For Azure uploads
      - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Setup Monaco Editor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          FULL_TAG_REF: ${{ github.ref }}
        run: "node ./publish-monaco-editor.js $(echo $FULL_TAG_REF | cut -d/ -f3)"

      - name: Upload to Azure
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: node ./upload-assets-to-blob-storage.js

      - name: Send a message to Microsoft Teams
        if: ${{ failure() }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEB_BOT_INCOMING_URL }}
          title: "Tagged Build failed for ${{ github.ref }}"
          summary: Failed to upload tag
          text: Failed to upload tag
          actions: '[{ "@type": "OpenUri", "name": "View Logs", "targets": [{ "os": "default", "uri": "https://github.com/microsoft/TypeScript-Make-Monaco-Builds/actions/runs/${{ github.run_id }}?check_suite_focus=true" }] }, { "@type": "OpenUri", "name": "Troubleshooting ", "targets": [{ "os": "default", "uri": "https://github.com/microsoft/TypeScript-Make-Monaco-Builds#troubleshooting" }] }]'
